import type { Metadata } from "next";
import { Poiret_One, Raleway, Roboto } from "next/font/google";
import StyledComponentsRegistry from "./StyledComponentsRegistry";
import Main from "./components/Main";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const poiretOne = Poiret_One({
  weight: "400",
  subsets: ["latin"],
});

const raleway = Raleway({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        lang="en"
        className={`${roboto.className} ${poiretOne.className} $ ${raleway.className}`}
      >
        <StyledComponentsRegistry>
          <Main>{children}</Main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
